### ISSUE TITLE
Auto salary slow

### ISSUE THREAD

**Issue by Dragoncca** [TrainerRoshi/Roshi-HHeroes-Trainer#18]
Hi Master Roshi. 

First thanks a lot for what you've done, it's a pure wonder.
i don't know if i'm the only one, but auto salary work a bit slow, correctly but slow, and when we have 300+ girls it can be a little issue when i want to watch for exemple a specific girl.

it's not urgent but if you can do something or maybe it's my browser ? i use google chrome, your script is updated and i clear cookies every time i see an update. 

thanks for your help have a good day / night 
Drag

**Comment by TrainerRoshi** [comment]
Hey Drag,

I don't like it either. I made it slow because Kinkoid have lost their minds and are banning people who collect too quickly. Which is stupid because you can click very quickly with your mouse. On my account I stopped collecting salary since I realized I can sell one green item for 2.4 million which is more than collecting from all my girls. So if your level is high enough, I recommend ignoring salary. Cash is pretty useless in this game anyway; you'll always have enough to upgrade girls, buy items and level up stats.

If you really really want to risk it, I can set the speed as a local storage variable and you can change it to however many milliseconds you want in the developer console, but you will go nuts finding the optimal value since the game locks you out for two hours if you go too fast.

Cheers!
Roshi

**Comment by Dragoncca** [comment]
Oh, that why ! 
i didn't know that. Thanks a lot. if i can change it to put it a bit fast then i will not say no. but please don't take to much of your time for this. By the way my screen can't display all your setting. it's just a feed back. when you have all on activate. let's see :) 
![image](https://user-images.githubusercontent.com/79576797/109042297-54a05180-76d0-11eb-9579-d1a8a653a6ce.png)

Again, Thanks a lot, i wish i can dev like you. 
Drag

**Comment by TrainerRoshi** [comment]
Yeah my screen too. I've been thinking of making the font smaller or of using two columns. In the mean time, you can hide the Clubs drop down, it doesn't turn off Clubs; only the square button with the blonde guy turns it on/off. Also for Clubs you don't need to turn on SORT, it always sorts for Clubs. And let me know if you want the golden ★SORT★ and ★DRAFT★ buttons gone. I left them there so people understand how my logic works, or maybe if you want just one specific champion sorted.

**Comment by Dragoncca** [comment]
True, that was just for your information, i'm not using it soften. since i got all girl on champion, thanks for the information. 
I didn't thinking so much about the SORT and DRAFT button because of that, but that so cool and helpfull, maybe select legendary over commun ? 
I thought i would sort girl by lvl, auto upgrade girl lvl, auto upgrade girl Aff.
Did the auto season select ramdom opponent ?
how work the stats upgrade (+ button) always up 30 times each ? (at lower lvl, if we don't start with script it always up a bit and stop. never maxed. 

I'm sorry, it turns into questioning ^^ 

Drag

**Comment by TrainerRoshi** [comment]
The girls are sorted by position and then by their damage. It keeps sorting and drafting until the first 6 positions are correct. 

The stat upgrade stops if you don't have 1,000,000 cash. You should leave the blue button to x1 to ensure a full upgrade.

There is a super secret auto upgrade function for books and gifts in the items menu, but you have to find out how to activate it. All the clues are in this video: https://www.youtube.com/watch?v=A7Te_nnv_58

For kiss fights, it selects the lowest level opponent of the three, but I'm gonna change it to select the lowest health (ego) opponent in the next update.

I like questions about the game and my script! Almost all of the comments I get are from people who don't know how to use Tampermonkey/Greasemonkey :'(
