### ISSUE TITLE
New Version of HH kilt Roshi

### ISSUE THREAD

**Issue by Sarewe** [TrainerRoshi/Roshi-HHeroes-Trainer#68]
The script does not work with the new version of HH. But it looks funny.
![Screenshot 2024-03-27 153455](https://github.com/TrainerRoshi/Roshi-HHeroes-Trainer/assets/139480538/01d77eda-723d-4eb2-8a56-db33dc1a0745)

**Comment by Sarewe** [comment]
Apparently the update has been cancelled. It is now working normally again.

**Comment by Sarewe** [comment]
The Problem is back.
![Screenshot 2024-04-02 172548](https://github.com/TrainerRoshi/Roshi-HHeroes-Trainer/assets/139480538/c150de89-7395-4598-bbe0-943a10d943c5)

**Comment by Sarewe** [comment]
The Problem ist back. 
![Screenshot 2024-04-02 172548](https://github.com/TrainerRoshi/Roshi-HHeroes-Trainer/assets/139480538/4a189f1c-9b7b-4b1c-8927-01cb40f7d180)

**Comment by TrainerRoshi** [comment]
Yeah. Roshi is scared. I hope it goes back again. Otherwise the website is completely new. Auto champions and auto blessings would need to be completely re-written. 
I can't even find the source (used to be named default.js) so I can understand how their website works. If anyone can point me to the new JavaScript file, I would really appreciate it.

**Comment by TrainerRoshi** [comment]
Ok all fixed! Roshi is an underappreciated genius. It should work even if the site goes back again.

**Comment by Sarewe** [comment]
Good job! Thank you.
